Repository dalek-cryptography/curve25519-dalek, pull requests merged in 2021-04, with the labels that each got.

#311 variable-sizes of precomputed tables for basepoint scalar multiplication
  src/edwards.rs
  src/ristretto.rs
  src/scalar.rs
  src/traits.rs
  src/window.rs
Labels: api - design, efficiency - memory, efficiency - speed, enhancement, research - cryptography, safety - type

#342 Serial backends w/formally-verified field arithmetic for 32 & 64 bits
  .travis.yml
  Cargo.toml
  src/backend/mod.rs
  src/backend/serial/fiat_u32/field.rs
  src/backend/serial/fiat_u32/mod.rs
  src/backend/serial/fiat_u64/field.rs
  src/backend/serial/fiat_u64/mod.rs
  src/backend/serial/mod.rs
  src/backend/serial/u32/constants.rs
  src/backend/serial/u64/constants.rs
  src/constants.rs
  src/field.rs
  src/lib.rs
  src/scalar.rs
Labels: enhancement, formal verification

#352 Implement Identity for MontgomeryPoint.
  src/montgomery.rs
Labels: api - pain point, enhancement
